interface FallbackReply { keywords: string[]; reply: string; }
const replies: FallbackReply[] = [
  { keywords: ['cramp', 'cramps', 'period pain', 'pelvic pain', 'aching', 'sore'], reply: "Cramps like this are exhausting, and it's completely fair to be over it right now. A heating pad or warm bath can help take the edge off. If you can, let yourself curl up somewhere warm for a bit." },
  { keywords: ['bloated', 'bloating', 'stomach', 'belly'], reply: "That bloated, tight feeling is so uncomfortable, and it makes sense you'd want relief. Some warm ginger or peppermint tea and gentle movement can feel comforting. Loose, comfortable clothing helps more than people admit too." },
  { keywords: ['tired', 'exhausted', 'fatigue', 'no energy', 'drained'], reply: "It's okay to be tired right now. You don't need to push through today at full speed. If you can, let yourself rest without guilt." },
  { keywords: ['anxious', 'anxiety', 'worried', 'nervous', 'panicking'], reply: "It sounds like your mind is racing, and that's a really uncomfortable place to be. Let’s slow down for one breath: in for 4, hold for 4, and out for 6. You don’t have to solve everything this minute." },
  { keywords: ['sad', 'crying', 'want to cry', 'down', 'low', 'upset'], reply: "It’s okay to feel this low. Whatever is coming up for you right now is valid. If crying is what your body needs, that’s alright too." },
  { keywords: ['angry', 'irritable', 'frustrated', 'snapping', 'annoyed', 'mood swing'], reply: "Feeling irritable like this is hard, and it is not a character flaw. You’re allowed to have a short fuse sometimes. Try to be as gentle with yourself as you can today." },
  { keywords: ['not believed', 'doctor dismissed', 'ignored', 'nobody listens', 'no one believes'], reply: "I’m sorry you’ve felt dismissed like that. What you’re feeling is real, whether or not it has been taken seriously yet. Your Case File is here so your own record can speak for you next time." },
  { keywords: ['lonely', 'alone', 'no one understands', 'isolated'], reply: "Feeling alone with this is hard. I’m glad you said something instead of sitting with it in silence. You’re not overreacting, and you’re not alone in this moment." },
  { keywords: ['overwhelmed', "can't cope", 'too much', 'breaking down'], reply: "It sounds like a lot is piling up right now. You don’t have to handle all of it at once—just this next minute is enough. Let’s take one slow breath before anything else." },
  { keywords: ["can't sleep", 'insomnia', 'awake all night', 'restless'], reply: "Not being able to sleep on top of everything else is rough. Try putting the phone down for a few minutes and letting your breathing slow: in for 4, out for 6. Rest still counts, even if sleep takes time." },
  { keywords: ['thank you', 'thanks', 'that helped', 'feel better'], reply: "I’m really glad that helped, even a little. You’re doing better than you’re giving yourself credit for right now." },
  { keywords: ['hi', 'hello', 'hey', 'just checking in'], reply: "Hi, I’m glad you’re here. How’s your body feeling right now, and how’s the rest of you doing today?" }
];
export function matchFallbackReply(message: string) { const lower = message.toLowerCase(); return replies.find(reply => reply.keywords.some(keyword => lower.includes(keyword)))?.reply ?? "I hear you. Whatever you’re feeling right now is valid, even if it’s hard to put into words. Want to tell me a little more, or would a moment of quiet together help more?"; }
