import { useEffect, useRef, useState } from 'react';
import { Icon } from './Icon';
import { useAISoother } from '../hooks/useAISoother';
const moods = ['achy today', 'just tired', 'feeling anxious', 'kind of sad', 'irritable'];
export function AISoother() {
  const { messages, send, sending } = useAISoother(); const [input, setInput] = useState(''); const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' }); }, [messages, sending]);
  const submit = (text: string) => { if (!text.trim() || sending) return; send(text.trim()); setInput(''); };
  return <section className="glass flex min-h-[430px] flex-col rounded-3xl p-5"><p className="text-xs text-rose-950/55">A warm space to check in. This is not therapy, diagnosis, or medical advice.</p>{messages.length === 0 ? <div className="flex flex-col items-center py-8 text-center"><div className="animate-[breathe_6s_ease-in-out_infinite] mb-5 grid h-28 w-28 place-items-center rounded-full bg-rose-200/50"><span className="h-16 w-16 rounded-full bg-rose-300/60" /></div><h2 className="font-display text-3xl italic text-rose-800">I’m here with you</h2><p className="mt-2 max-w-xs text-sm text-rose-950/60">Tell me how you’re feeling, or pick one below to start.</p></div> : null}<div ref={scrollRef} className="mb-4 flex-1 space-y-3 overflow-y-auto px-1">{messages.map((message, index) => <div key={index} className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[82%] rounded-3xl px-5 py-3 text-sm leading-relaxed ${message.role === 'user' ? 'rounded-br-lg bg-rose-800 text-white' : message.isCrisis ? 'rounded-bl-lg border border-blush-400 bg-blush-100 text-rose-950' : 'glass rounded-bl-lg text-rose-950'}`}>{message.content}{message.isCrisis ? <div className="mt-3 flex gap-2"><a href="tel:9152987821" className="rounded-full bg-white/70 px-3 py-1.5 text-xs font-semibold"><Icon name="call" size={14} /> iCall</a><a href="tel:18005990019" className="rounded-full bg-white/70 px-3 py-1.5 text-xs font-semibold"><Icon name="call" size={14} /> KIRAN</a></div> : null}</div></div>)}{sending ? <div className="flex justify-start"><div className="glass flex gap-1.5 rounded-3xl rounded-bl-lg px-5 py-3">{[0,1,2].map(index => <span key={index} className="h-1.5 w-1.5 animate-bounce rounded-full bg-rose-400" style={{ animationDelay: `${index * .15}s` }} />)}</div></div> : null}</div>{messages.length === 0 ? <div className="mb-4 flex flex-wrap gap-2">{moods.map(mood => <button key={mood} onClick={() => submit(mood)} className="rounded-full bg-rose-100 px-4 py-2 text-xs font-semibold text-rose-800 transition hover:bg-rose-200">{mood}</button>)}</div> : null}<div className="flex gap-2"><input value={input} onChange={event => setInput(event.target.value)} onKeyDown={event => event.key === 'Enter' && submit(input)} placeholder="How are you feeling right now?" className="min-w-0 flex-1 rounded-full border border-rose-200/60 bg-white/70 px-5 py-3 text-sm text-rose-950 placeholder:text-rose-950/40 focus:outline-none focus:ring-2 focus:ring-rose-300" /><button aria-label="Send" onClick={() => submit(input)} disabled={sending || !input.trim()} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-rose-800 text-white disabled:bg-rose-200"><Icon name="send" size={18} /></button></div></section>;
}
