import { useMemo, useState } from 'react';
import type { Entry } from '../lib/types';
import { usePeriodLog } from '../hooks/usePeriodLog';
import { Icon } from './Icon';
const toKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const localDate = (key: string) => new Date(`${key}T12:00:00`);
export function CycleCalendar({ entries, compact = false }: { entries: Entry[]; compact?: boolean }) {
  const { logs, startPeriod, endPeriod, isOnPeriod, predictedNextPeriod, currentCycleDay } = usePeriodLog(); const [month, setMonth] = useState(() => new Date()); const [selected, setSelected] = useState(toKey(new Date())); const today = toKey(new Date());
  const periodDays = useMemo(() => { const days = new Set<string>(); logs.forEach(log => { const cursor = localDate(log.start_date); const end = localDate(log.end_date ?? today); while (cursor <= end) { days.add(toKey(cursor)); cursor.setDate(cursor.getDate() + 1); } }); return days; }, [logs, today]);
  const severity = useMemo(() => { const result = new Map<string, number>(); entries.forEach(entry => { const day = entry.created_at.slice(0, 10); const value = Math.max(...entry.tags.map(tag => tag.severity), 0); result.set(day, Math.max(result.get(day) ?? 0, value)); }); return result; }, [entries]);
  const dayCount = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const blanks = new Date(month.getFullYear(), month.getMonth(), 1).getDay(); const active = logs.find(log => log.end_date === null); const cycleDay = currentCycleDay(); const prediction = predictedNextPeriod; const canSelect = (key: string) => key <= today;
  const changeMonth = (offset: number) => setMonth(current => new Date(current.getFullYear(), current.getMonth() + offset, 1));
  return <section className={`glass mt-5 rounded-3xl ${compact ? 'p-4' : 'p-6'}`}><div className="flex items-center justify-between"><button aria-label="Previous month" onClick={() => changeMonth(-1)}><Icon name="chevron_left" className="text-rose-800" /></button><h2 className="font-display text-xl italic text-rose-800">{month.toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</h2><button aria-label="Next month" onClick={() => changeMonth(1)}><Icon name="chevron_right" className="text-rose-800" /></button></div><p className="mt-2 text-center text-xs text-rose-950/50">Choose a date, then mark a period start or end.</p><div className="mt-4 grid grid-cols-7 gap-1 text-center text-xs text-rose-950/45">{['S','M','T','W','T','F','S'].map((day, index) => <span key={`${day}${index}`}>{day}</span>)}</div><div className="mt-1 grid grid-cols-7 gap-1">{Array.from({ length: blanks }).map((_, index) => <span key={`blank-${index}`} />)}{Array.from({ length: dayCount }, (_, index) => { const day = index + 1; const key = toKey(new Date(month.getFullYear(), month.getMonth(), day)); const onPeriod = periodDays.has(key); const predicted = prediction?.date === key; const level = severity.get(key); const disabled = !canSelect(key); return <button disabled={disabled} onClick={() => setSelected(key)} key={key} className={`relative grid aspect-square place-items-center rounded-full text-xs transition ${onPeriod ? 'bg-rose-500 text-white' : predicted ? 'border border-dashed border-rose-400 text-rose-600' : 'text-rose-950/75'} ${key === today ? 'ring-2 ring-rose-800 ring-offset-1 ring-offset-rose-50' : ''} ${key === selected ? 'outline outline-2 outline-rose-700 outline-offset-1' : ''} ${disabled ? 'cursor-not-allowed opacity-30' : 'hover:bg-rose-100'}`}>{day}{level && !onPeriod ? <i className="absolute bottom-0.5 h-1 w-1 rounded-full bg-blush-500" style={{ opacity: level / 5 }} /> : null}</button>; })}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 text-sm">{isOnPeriod && active ? <button onClick={() => endPeriod(active.id, selected)} disabled={selected < active.start_date || selected > today} className="inline-flex items-center gap-1.5 font-semibold text-rose-800 disabled:opacity-40"><Icon name="water_drop" size={18} filled />Mark period ended</button> : <button onClick={() => startPeriod(selected)} disabled={selected > today} className="inline-flex items-center gap-1.5 font-semibold text-rose-800 disabled:opacity-40"><Icon name="water_drop" size={18} />Log period start</button>}<span className="text-xs text-rose-950/55">{prediction ? `Next period estimated around ${localDate(prediction.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}` : cycleDay ? `Cycle day ${cycleDay} · add another completed period to estimate timing` : 'Log a period start to add cycle context'}</span></div><p className="mt-3 text-xs text-rose-950/45">Predictions are estimates from your logged dates, not medical advice.</p></section>;
}
