import { useState } from 'react';
import { ChevronDown, Check, Plus } from 'lucide-react';
import type { TagEntry } from '../lib/types';
const groups = [
  ['Pain', ['pelvic_pain', 'joint_pain', 'headache', 'back_pain']], ['Energy & Mind', ['fatigue', 'brain_fog', 'sleep_disturbance', 'dizziness']], ['Digestive', ['bloating', 'nausea', 'digestive_issue']], ['Physical Changes', ['skin_change', 'hair_loss', 'fever']], ['Mood', ['mood_change']]
] as const;
const label = (tag: string) => tag.replace(/_/g, ' ').replace(/\b\w/g, (char: string) => char.toUpperCase());
export function JourneyLogger({ onSave, onNext }: { onSave: (tags: TagEntry[]) => Promise<unknown>; onNext: () => void }) {
  const [open, setOpen] = useState<string>('Pain'); const [selected, setSelected] = useState<Record<string, number>>({}); const [other, setOther] = useState(''); const [saving, setSaving] = useState(false); const selectedTags: TagEntry[] = Object.entries(selected).map(([tag, severity]) => ({ tag, severity })); if (other.trim()) selectedTags.push({ tag: 'other', severity: selected.other ?? 3, note: other.trim() });
  const toggle = (tag: string) => setSelected(current => current[tag] ? Object.fromEntries(Object.entries(current).filter(([key]) => key !== tag)) : { ...current, [tag]: 3 });
  const submit = async () => { if (!selectedTags.length) return; setSaving(true); try { await onSave(selectedTags); setSelected({}); setOther(''); onNext(); } finally { setSaving(false); } };
  return <section className="space-y-3"><p className="text-rose-600">Pick what you noticed. Severity starts at 3 and can be changed before you log.</p>{groups.map(([name, tags]) => <div key={name} className="rounded-2xl border border-rose-200 bg-white/75 overflow-hidden"><button onClick={() => setOpen(open === name ? '' : name)} className="w-full flex justify-between items-center px-5 py-4 text-left font-semibold text-rose-800"><span>{name}</span><ChevronDown className={`h-4 w-4 transition-transform ${open === name ? 'rotate-180' : ''}`} /></button>{open === name && <div className="px-5 pb-5 flex flex-wrap gap-2">{tags.map(tag => <div key={tag} className={`rounded-xl border px-3 py-2 ${selected[tag] ? 'border-rose-400 bg-rose-50' : 'border-rose-100'}`}><button onClick={() => toggle(tag)} className="text-sm text-rose-700">{selected[tag] && <Check className="inline w-3.5 mr-1" />}{label(tag)}</button>{selected[tag] && <label className="ml-2 text-xs text-rose-500">Severity <select value={selected[tag]} onChange={event => setSelected(current => ({ ...current, [tag]: Number(event.target.value) }))} className="bg-transparent font-bold">{[1,2,3,4,5].map(value => <option key={value}>{value}</option>)}</select></label>}</div>)}</div>}</div>)}<div className="rounded-2xl border border-rose-200 bg-white/75 p-5"><label className="font-semibold text-rose-800 block mb-2">Something else</label><input value={other} onChange={event => setOther(event.target.value)} className="w-full rounded-xl border border-rose-200 px-3 py-2 text-sm" placeholder="Write it in your own words" /></div><button disabled={!selectedTags.length || saving} onClick={submit} className="w-full rounded-xl bg-rose-600 py-3 font-semibold text-white disabled:opacity-50">{saving ? 'Saving your entry…' : 'Log symptoms'} <Plus className="inline w-4" /></button></section>;
}
