import { useState } from 'react';
import type { TagEntry } from '../lib/types';
import { Icon } from './Icon';
const groups = [['Pain', ['pelvic_pain', 'joint_pain', 'headache', 'back_pain']], ['Energy & Mind', ['fatigue', 'brain_fog', 'sleep_disturbance', 'dizziness']], ['Digestive', ['bloating', 'nausea', 'digestive_issue']], ['Physical Changes', ['skin_change', 'hair_loss', 'fever']], ['Mood', ['mood_change']]] as const;
const label = (tag: string) => tag.replace(/_/g, ' ').replace(/\b\w/g, (char: string) => char.toUpperCase());
export function JourneyLogger({ cycleDay, onSave, onNext }: { cycleDay: number | null; onSave: (tags: TagEntry[]) => Promise<unknown>; onNext: () => void }) {
  const [open, setOpen] = useState<string>('Pain'); const [selected, setSelected] = useState<Record<string, number>>({}); const [other, setOther] = useState(''); const [saving, setSaving] = useState(false); const tags: TagEntry[] = Object.entries(selected).map(([tag, severity]) => ({ tag, severity })); if (other.trim()) tags.push({ tag: 'other', severity: 3, note: other.trim() });
  const toggle = (tag: string) => setSelected(current => current[tag] ? Object.fromEntries(Object.entries(current).filter(([key]) => key !== tag)) : { ...current, [tag]: 3 });
  const submit = async () => { if (!tags.length) return; setSaving(true); try { await onSave(tags); setSelected({}); setOther(''); onNext(); } finally { setSaving(false); } };
  return <section className="mt-5 space-y-3"><div className="flex items-center justify-between rounded-2xl bg-rose-100/70 px-4 py-3 text-sm text-rose-800"><span className="inline-flex items-center gap-2"><Icon name="calendar_month" size={18} />{cycleDay ? `Cycle day ${cycleDay}` : 'No cycle day attached'}</span><span className="text-xs text-rose-600">Set in your calendar</span></div><p className="text-rose-700">Pick what you noticed. Severity starts at 3 and can be changed before you log.</p>{groups.map(([name, groupTags]) => <div key={name} className="overflow-hidden rounded-2xl border border-rose-200 bg-white/75"><button onClick={() => setOpen(open === name ? '' : name)} className="flex w-full items-center justify-between px-5 py-4 text-left font-semibold text-rose-800"><span>{name}</span><Icon name="expand_more" className={open === name ? 'rotate-180 transition-transform' : 'transition-transform'} /></button>{open === name ? <div className="flex flex-wrap gap-2 px-5 pb-5">{groupTags.map(tag => <div key={tag} className={`rounded-xl border px-3 py-2 ${selected[tag] ? 'border-rose-400 bg-rose-50' : 'border-rose-100'}`}><button onClick={() => toggle(tag)} className="text-sm text-rose-700">{selected[tag] ? <Icon name="check" size={14} className="mr-1 align-middle" /> : null}{label(tag)}</button>{selected[tag] ? <label className="ml-2 text-xs text-rose-500">Severity <select value={selected[tag]} onChange={event => setSelected(current => ({ ...current, [tag]: Number(event.target.value) }))} className="bg-transparent font-bold">{[1,2,3,4,5].map(value => <option key={value}>{value}</option>)}</select></label> : null}</div>)}</div> : null}</div>)}<div className="rounded-2xl border border-rose-200 bg-white/75 p-5"><label className="mb-2 block font-semibold text-rose-800">Something else</label><input value={other} onChange={event => setOther(event.target.value)} className="w-full rounded-xl border border-rose-200 px-3 py-2 text-sm" placeholder="Write it in your own words" /></div><button disabled={!tags.length || saving} onClick={submit} className="w-full rounded-xl bg-rose-800 py-3 font-semibold text-white transition hover:bg-rose-700 disabled:opacity-50">{saving ? 'Saving your entry…' : 'Log symptoms'} <Icon name="add" size={17} className="align-middle" /></button></section>;
}
